/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/likeyou` | `/likeyou`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/update-profile` | `/update-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/chat/[matchId]` | `/chat/[matchId]`, params: Router.UnknownInputParams & { matchId: string | number; } } | { pathname: `${'/(main)'}/chat/call/[callID]` | `/chat/call/[callID]`, params: Router.UnknownInputParams & { callID: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/likeyou` | `/likeyou`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/update-profile` | `/update-profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/chat/[matchId]` | `/chat/[matchId]`, params: Router.UnknownOutputParams & { matchId: string; } } | { pathname: `${'/(main)'}/chat/call/[callID]` | `/chat/call/[callID]`, params: Router.UnknownOutputParams & { callID: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/likeyou${`?${string}` | `#${string}` | ''}` | `/likeyou${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/update-profile${`?${string}` | `#${string}` | ''}` | `/update-profile${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/likeyou` | `/likeyou`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/update-profile` | `/update-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | `${'/(main)'}/chat/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/chat/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/chat/call/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/chat/call/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(main)'}/chat/[matchId]` | `/chat/[matchId]`, params: Router.UnknownInputParams & { matchId: string | number; } } | { pathname: `${'/(main)'}/chat/call/[callID]` | `/chat/call/[callID]`, params: Router.UnknownInputParams & { callID: string | number; } };
    }
  }
}
